exclude_paths:
  - src/main/resources
  - docs
  - gradle
  - README.md
  - '*.gradle'
  - '*.bat'

engines:
  checkstyle:
    enabled: true
    language: java

  pmd:
    enable: true
    language: java
