exclude_paths:
  - src/main/resources
  - docs
  - gradle
  - '*.md'
  - '**.gradle'
  - '**.bat'

engines:
  checkstyle:
    enabled: true
    language: java
    exclude_paths:
      - README.md

  pmd:
    enable: true
    language: java
    exclude_paths:
      - README.md
