version: '{build}'
skip_tags: true

#os: Windows Server 2012
image:
- Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

build_script:
  - gradlew.bat clean assemble --info --no-daemon --stacktrace

test_script:
  - gradlew.bat check test --info --no-daemon --stacktrace

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
  fast_finish: true
