version: '{build}'
skip_tags: true

image:
- Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

build_script:
  - gradlew.bat check --info

test_script:
  - gradlew.bat clean test --info

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
  fast_finish: true
